### ISSUE TITLE
Upload status

### ISSUE THREAD

**Issue by tscung** [Azure/azure-storage-android#7]
Is there anyway to get the upload status. We need to find out if the blob is uploaded successfully,

**Comment by leleliu008** [comment]
java.lang.OutOfMemoryError
	at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:156)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:288)
	at com.microsoft.azure.storage.core.Utility.writeToOutputStream(Utility.java:1218)
	at com.microsoft.azure.storage.core.Utility.writeToOutputStream(Utility.java:1130)
	at com.microsoft.azure.storage.blob.BlobOutputStream.write(BlobOutputStream.java:525)
	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:583)
	at com.microsoft.azure.storage.blob.CloudBlob.uploadFromFile(CloudBlob.java:1837)
	at com.microsoft.azure.storage.blob.CloudBlob.uploadFromFile(CloudBlob.java:1809)
	at com.datatang.client.framework.storage.AzureStorage.uploadFile(AzureStorage.java:135)
	at com.datatang.client.framework.upload.service.UploadBinder$2.run(UploadBinder.java:110)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

**Comment by emgerner-msft** [comment]
@tscung Closing as this has been open 2 years now. Feel free to reopen if needed, or open a new issue with additional questions.
